flask_app/python/models.py
from flask_app import db
from datetime import datetime


class Data(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    temperature = db.Column(db.Float, unique=False, nullable=False)
    humidity = db.Column(db.Float, unique=False, nullable=False)
    humidifier_state = db.Column(db.Integer, unique=False, nullable=False)
    time = db.Column(db.DateTime, default=datetime.utcnow, unique=False, nullable=False)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'temperature': self.temperature,
            'humidity': self.humidity,
            'humidifier_state': self.humidifier_state,
            'time': self.time,
        }

class SetPoint(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    humidity_set_point = db.Column(db.Float, unique=False, nullable=False)
    humidity_deviation = db.Column(db.Float, unique=False, nullable=False)

    @property
    def serialize(self):
        return {
            'humidity_set_point': self.humidity_set_point,
            'humidity_deviation': self.humidity_deviation,
        }

class LastStatus(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    humidity = db.Column(db.Float, unique=False, nullable=False)
    temperature = db.Column(db.Float, unique=False, nullable=False)
    humidifier_state = db.Column(db.Integer, unique=False, nullable=False)

    @property
    def serialize(self):
        return {
            'humidity': self.humidity,
            'temperature': self.temperature,
            'humidifier_state': self.humidifier_state,
        }

flask_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

####### RESTART DB? #######
RESTART_DB = False
###########################

db = SQLAlchemy()

def create_app(config_class):
    app = Flask(__name__)

    print(f"STARTING CONFIG MODE: {config_class.MODE}")
    app.config.from_object(config_class)

    app.config["auto_control_humidity"] = True
    app.config["humidifier_state"] = False
    
    db.init_app(app)

    from flask_app.python.main.routes import main
    app.register_blueprint(main)

    print("\nRestart DB set to:", RESTART_DB, '\n')
    
    from flask_app.python.models import SetPoint, LastStatus
    if RESTART_DB is True:
        with app.app_context():
            print("Dropando tabelas")
            db.drop_all()
            print("Criando tabelas")
            db.create_all()
            set_point = SetPoint(
                humidity_set_point = 60.0,
                humidity_deviation = 2.0,
            )
            last = LastStatus(
                humidity = 60.0,
                temperature = 25.0,
                humidifier_state = 0
            )
            db.session.add(set_point)
            db.session.add(last)
            db.session.commit()
            print("Banco de dados restaurado. \n")

    return app

flask_app/python/main/routes.py
from flask import current_app, Blueprint, render_template, send_file, jsonify, request
from flask_app import db
from flask_app.python.models import Data, SetPoint, LastStatus
from flask_app.python.main.utils import update_last_status, humidifier

from datetime import datetime
import Adafruit_DHT
import csv

main = Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html', title='Controle de Umidade')

@main.route('/get-data', methods=['GET'])
def get_data():
	data = Data.query.all()
	size = 60
	if len(data)<size:
		size = len(data)
	temps=[]
	hums=[]
	times=[]
	states=[]
	for i in range(-size, 0):
		temps.append(data[i].serialize["temperature"])
		hums.append(data[i].serialize["humidity"])
		times.append(data[i].serialize["time"])
		states.append(data[i].serialize["humidifier_state"])

	data = {
		"temperature": temps,
		"humidity": hums,
		"time": times,
		"humidifier_state": states,
	}

	return(data)

@main.route('/get-csv-db', methods=['GET'])
def get_csv_db():
	data = Data.query.all()
	header = ["timestamp", "temperatura", "umidade", "estado_do_umidificador"]
	rows = []
	for d in data:
		rows.append([
			d.serialize["time"],
			d.serialize["temperature"], 
			d.serialize["humidity"], 
			d.serialize["humidifier_state"]
		])

	path = 'banco_de_dados.csv'
	with open(f"flask_app/{path}", 'w', encoding='UTF8') as f:
		writer = csv.writer(f)
		writer.writerow(header)
		writer.writerows(rows)
		
	return send_file(path, as_attachment=True)

@main.route('/get-last-status', methods=['GET'])
def get_last_status():
	last = db.session.query(LastStatus).get(1).serialize
	last["auto_control"] = current_app.config["auto_control_humidity"]
	return(last)

@main.route('/get-set-point', methods=['GET'])
def get_set_point():
    set_point = db.session.query(SetPoint).get(1)
    return(set_point.serialize)

@main.route('/post-update-info', methods=['POST'])
def post_update_info():
	data = request.get_json()

	set_point = db.session.query(SetPoint).get(1)
	if set_point:
		set_point.humidity_set_point = data['humidity_set_point']
		set_point.humidity_deviation = data['humidity_deviation']
	else:
		set_point = SetPoint(
				humidity_set_point = data['humidity_set_point'],
				humidity_deviation = data['humidity_deviation'],
			)
		db.session.add(set_point)
	db.session.commit()
	return(data)

@main.route('/post-update-auto-control', methods=['POST'])
def post_update_auto_control():
	data = request.get_json()
	current_app.config["auto_control_humidity"] = data['auto_control']
	print(current_app.config["auto_control_humidity"])
	return({'auto_control': current_app.config["auto_control_humidity"]})

@main.route('/post-humi-on-off', methods=['POST'])
def post_humi_on_off():
	data = request.get_json()
	
	last = get_last_status()
	if last['humidifier_state'] == 1:
		humidifier(0)
		update_last_status(last['humidity'], last['temperature'])
		return({'humi_state': False})
	else:
		humidifier(1)
		update_last_status(last['humidity'], last['temperature'])
		return({'humi_state': True})

flask_app/templates/index.html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='imgs/humidity_fav.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='imgs/humidity_fav.png') }}" rel="apple-touch-icon">

  {% if title %}
    <title>{{ title }}</title>
  {% else %}
    <title>Controle de Umidade</title>
  {% endif %}
  
  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">

  <!-- import plugin script -->
  <script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/chart.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
</head>

<body>
  <main>
    <div class="container py-4">
      <header class="pb-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
          <img src="{{ url_for('static', filename='imgs/humidity.png') }}" alt="" width="50" height="50" class="d-inline-block align-text-top mr-4">
          <span class="ms-3 fs-3">Controle de Umidade</span>
        </a>
      </header>
  
      <div class="p-2 mb-2 bg-light rounded-1">
        <div class="row justify-content-md-center">
          <div class="col-lg-auto">
            <a href="javascript:void(0)" class="d-flex align-items-center text-dark text-decoration-none">
              <img src="{{ url_for('static', filename='imgs/icons/thermometer.png') }}" alt="" width="50" height="40" class="d-inline-block align-text-top mr-4">
              <span id="temp-atual-value" class="ms-3 fs-5"></span>
            </a>
          </div>
          <div class="col-lg-auto">
            <a href="javascript:void(0)" class="d-flex align-items-center text-dark text-decoration-none">
              <img src="{{ url_for('static', filename='imgs/icons/humidity.png') }}" alt="" width="50" height="40" class="d-inline-block align-text-top mr-4">
              <span id="humi-atual-value"  class="ms-3 fs-5"></span>
            </a>
          </div>
          <div class="col-lg-auto">
            <a href="javascript:void(0)" class="d-flex align-items-center text-dark text-decoration-none">
              <img src="{{ url_for('static', filename='imgs/icons/switch.png') }}" alt="" width="50" height="40" class="d-inline-block align-text-top mr-4">
              <span id="humistate-atual-value" class="ms-3 fs-5"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="p-2 mb-2 bg-light rounded-1">
        <div class="row justify-content-center">
          <div class="col-auto">
            <h2 class="fs-5">Controle Automático</h2>
            <div class="my-3">
              <div class="form-check">
                <input id="auto-control-on-input" name="autoControl" type="radio" class="form-check-input" checked required>
                <label class="form-check-label" for="auto-control-on-input">Ativado</label>
              </div>
              <div class="form-check">
                <input id="auto-control-off-input" name="autoControl" type="radio" class="form-check-input" required>
                <label class="form-check-label" for="auto-control-off-input">Desativado</label>
              </div>
            </div>
            <h2 id="on-off-label" style="display: none;" class="mb-2 fs-5">Umidificador</h2>
            <div class="d-flex justify-content-center">
              <button style="display: none;" id="ligar-desligar-humi" class="w-50 mt-2 btn btn-primary" type="submit"></button>
            </div>
          </div>
          <div class="col-2">
          </div>
          <div class="col-auto mb-2">
            <h2 class="fs-5 mb-2">Parâmetros de controle</h2>
            <div class="mb-3">
              <label for="umidade-desejada-input" class="form-label">Umidade desejada [%]</label>
              <input type="number" class="form-control" id="umidade-desejada-input">
            </div>
            <div class="mb-3">
              <label for="variacao-maxima-input" class="form-label">Variação máxima permitida [%]</label>
              <input type="number" class="form-control" id="variacao-maxima-input">
            </div>
            <div class="d-flex justify-content-center">
              <button id="update-info" class="w-50 mt-2 btn btn-primary" type="submit">Aplicar</button>
            </div>
          </div>
        </div>
      </div>

      <div class="row align-items-md-stretch">
        <div class="col-md-6">
          <div class="container-sm">
            <canvas id="Temp_chart" width="600" height="400"></canvas>
          </div>
        </div>
        <div class="col-md-6">
          <div class="container-sm">
            <canvas id="Hum_chart" width="600" height="400"></canvas>
          </div>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-auto mb-2">
          <div class="d-flex justify-content-center">
            <button type="button" class="btn btn-primary btn-sm mt-3" id="download-csv" onclick="window.location.href='{{ url_for('main.get_csv_db') }}';">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
              <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"></path>
              <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"></path>
              </svg>
              Exportar dados em CSV
            </button>
          </div>
        </div>
      </div>
      <footer class="pt-3 mt-4 text-muted border-top">
      </footer>
    </div>
  </main>

</body>

<footer>
  <script src="{{ url_for('static', filename='js/general.js') }}">
  </script>
  
</footer>